### ISSUE TITLE
SPI conflicts

### ISSUE THREAD

**Issue by Jay-esp** [RobTillaart/DAC8551#11]
Hello,

My use case is an esp32 with dac8501 module and ad9833 module on spi bus HSPI, there seems to be some conflict, the 8501 works but the 9833 does not, if i run the example code for the 9833 that works, the 8501 driver seems to configure the spi bus so that the 9833 code does no longer work, if i look at the data/clock/sync signals of the 9833 on a scope i get no action, data and clock stay low, sync high, no changes. Both devices are write only, removing the dac module has no effect, disabling the dac.begin does, any clues?

**Comment by Jay-esp** [comment]
Hi,

Yes, the example sketch for the ad9833 works fine, the final sketch for my project works fine with the dac but the spi to the ad9833 is completely dead, no signals at all.

this is the library

https://www.arduino.cc/reference/en/libraries/md_ad9833/

sketch is a bit long to post

**Comment by RobTillaart** [comment]
mmmm,

can you try

```cpp
#include <SPI.h>
#include <MD_AD9833.h>
#include <DAC8551.h>

DAC8501 DAC(16);
MD_AD9833 AD9833(17); 

void setup(void)
{

  DAC.selectHSPI();
  DAC.begin();
  DAC.setValue(0);

  AD9833.begin();
  AD9833.setMode(MD_AD9833::MODE_SINE);
  AD9833.setFrequency(MD_AD9833::CHAN_0, 5000);
  AD9833.setActiveFrequency(MD_AD9833::CHAN_0);
}

void loop(void)
{
  for (int x = 0 ; x < 10000 ; x++ ) {
    AD9833.setFrequency(MD_AD9833::CHAN_0, x + 1000);
    AD9833.setActiveFrequency(MD_AD9833::CHAN_0);
  }
}
```

**Comment by Jay-esp** [comment]
Tried that but the default bus is the other one so i do get signals on that bus.

I tried the following, forcing the data and clk lines as output but still the same, pulsing fsync(select) but low on clk and data

#include <MD_AD9833.h>
#include <SPI.h>
#include <DAC8551.h>

DAC8501 DAC(16);

// Pins for SPI comm with the AD9833 IC
#define AD9833_DATA  13  ///< SPI Data pin number
#define AD9833_CLK   14  ///< SPI Clock pin number
#define AD9833_FSYNC 17  ///< SPI Load pin number (FSYNC in AD9833 usage)

MD_AD9833 AD9833(AD9833_DATA, AD9833_CLK, AD9833_FSYNC); // Arbitrary SPI pins

#define UNKNOWN_PIN 0xFF

void setup(void)
{
  Serial.begin(115200); /* prepare for possible serial debug */



  DAC.selectHSPI();
  DAC.begin();
  //  DAC.setValue(0);

  AD9833.begin();
  AD9833.setMode(MD_AD9833::MODE_SINE);
  AD9833.setFrequency(MD_AD9833::CHAN_0, 5000);
  AD9833.setActiveFrequency(MD_AD9833::CHAN_0);



}

void loop(void)
{
  for (int x = 0 ; x < 10000 ; x++ ) {
    pinMode(AD9833_DATA, OUTPUT);
    pinMode(AD9833_CLK, OUTPUT);

    digitalWrite(AD9833_DATA, HIGH);
    delay(5);


    AD9833.setFrequency(MD_AD9833::CHAN_0, x + 1000);
    AD9833.setActiveFrequency(MD_AD9833::CHAN_0);
  }
}

**Comment by Jay-esp** [comment]
i even tried to force the data and clk pins as output in the md9833 driver and force them high but on the scope they stay low
i usually can figure out issues with drivers but this one.....
if i rem out the 8501 begin line then it works fine
what could make the spi pins on the esp32 to be forced low no matter what?


    digitalWrite(_fsyncPin, LOW);

	
    for (uint8_t i = 0; i < 16; i++)
    {
	   pinMode(_dataPin, OUTPUT);
     pinMode(_clkPin, OUTPUT);
digitalWrite(_dataPin, HIGH);
digitalWrite(_clkPin, HIGH);
	
      digitalWrite(_dataPin, (data & 0x8000) ? HIGH : LOW);
      digitalWrite(_clkPin, LOW); //data is valid on falling edge
      digitalWrite(_clkPin, HIGH);
      data <<= 1; // one less bit to do
    }
    digitalWrite(_dataPin, LOW); //idle low
    digitalWrite(_fsyncPin, HIGH);
  }
}

**Comment by RobTillaart** [comment]
I still do not trust the SPI_MODE _1 and SPI_MODE_2 .conflict.
We need to set the clock right before sending. (think ...)

**Comment by RobTillaart** [comment]
something like this?

```cpp
#include <MD_AD9833.h>
#include <SPI.h>
#include <DAC8551.h>

DAC8501 DAC(13, 14, 16);  // SW SPI
MD_AD9833 AD9833(17);   // HW SPI

#define UNKNOWN_PIN 0xFF

void setup(void)
{
  Serial.begin(115200); /* prepare for possible serial debug */

  DAC.selectHSPI();
  DAC.begin();
  //  DAC.setValue(0);

  AD9833.begin();
  AD9833.setMode(MD_AD9833::MODE_SINE);
  AD9833.setFrequency(MD_AD9833::CHAN_0, 5000);
  AD9833.setActiveFrequency(MD_AD9833::CHAN_0);
}

void loop(void)
{
  for (int x = 0 ; x < 10000 ; x++ ) {
    digitalWrite(14, HIGH);                         // set the clock line so it will have a falling edge for MODE_2
    AD9833.setFrequency(MD_AD9833::CHAN_0, x + 1000);
    AD9833.setActiveFrequency(MD_AD9833::CHAN_0);
  }
}
```

**Comment by Jay-esp** [comment]
Hi Rob, i included those settings to be on the safe side but they are redundant. It seems to work fine, i had a I2C DAC in the project but that was too slow so changed to SPI. Project is a HF/LF generator, i basically needed a sweep generator to adjust MF circuits in old radios at 455khz and 10.7mhz, i already had a good HF generator but it lacks sweep, i have a LF generator that covers upto 20MHz with sweep but it has no markers so i made one myself and while at it i include a load of other functions as well, here are a few pics, the DAC takes care of the sawtooth signal for the sweep sync

![IMG_6388](https://user-images.githubusercontent.com/58309071/137483915-ca24f455-4fa5-45ee-92a6-c8752a8529b5.JPG)
![IMG_6387](https://user-images.githubusercontent.com/58309071/137483929-715f4bf8-b9aa-4753-b316-4fad15475bfc.JPG)

**Comment by RobTillaart** [comment]
Welcome, feel free to reopen issues if needed, or if you are in need of a (faster) library I like challenges :)
