### ISSUE TITLE
ESP32 Demo

### ISSUE THREAD

**Issue by guaizai2023** [RobTillaart/DAC8551#15]
In platform io,I take this library,I try to use it for my ESP32,But when I Use like this
```cpp
#include "DAC8551.h"
#include "Wire.h"
DAC8531 mydac(1);
void setup()
{
  Serial.begin(115200);
  selectVSPI();
  mydac.begin();
}
```
The IDE will ERROR about 'selectVSPI' was not declared in this scope.
Would you please give me a true example for HW to ESP32?

----
updated post for code readability

**Comment by RobTillaart** [comment]
Thanks for the issue.
At the moment I'm very busy working on other issues in other libraries, so it might take a few days.
Sorry for the inconvenience.

**Comment by RobTillaart** [comment]
Had a quick look, you forgot to use the object

```cpp
//
//    FILE: DAC8551_ESP32_VSPI.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo DAC8551 library Arduino with hardware SPI
//     URL: https://github.com/RobTillaart/DAC8551


#include "DAC8551.h"
#include "Wire.h"

// HW SPI uses slave spin since 0.2.0
DAC8531 mydac(1);


void setup()
{
  Serial.begin(115200);
  mydac.selectVSPI();
  mydac.begin();
}


void loop()
{
  // minimal sawtooth
  for (uint16_t val = 0; val < 65500; val += 30)
  {
    mydac.setValue(val);
    int av = analogRead(A0);

    Serial.print(val);
    Serial.print("\t ==> \t");
    Serial.print(av);
    if (val % 300 == 0) Serial.println();
  }
  Serial.println();

  // minimal sinus
  for (long i = 0; i < 360; i++ )
  {
    long s = 32768 + 32768 * sin( i * (PI / 180.0));
    mydac.setValue(s);
    int av = analogRead(A0);
    Serial.print(i);
    Serial.print("\t ==> \t");
    Serial.print(av);
    delay(100);
    if (i % 30 == 0) Serial.println();
  }
  Serial.println();
}


// -- END OF FILE --
```

Compiles for ESP32 (not tested any further, 
Will add this as an extra example if it works for you

**Comment by guaizai2023** [comment]
Thank you very much!

**Comment by RobTillaart** [comment]
Please let me know if it works.

**Comment by guaizai2023** [comment]
I used the following statement, the DAC8531 module I made by myself correctly output 0.2V, maybe the module I made was wrong, the dac8531 burned out 5 seconds after the output voltage.
`#include "DAC8551.h"
#include "Wire.h"
DAC8531 mydac(10);
void setup()
{
  Serial.begin(115200);
  mydac.selectVSPI();
  mydac.begin();
}
void loop()
{    
mydac.setValue(150);
}

**Comment by guaizai2023** [comment]
I used the following statement, the DAC8531 module I made by myself correctly output 0.2V, maybe the module I made was wrong, the dac8531 burned out 5 seconds after the output voltage.
`#include "DAC8551.h"
#include "Wire.h"
DAC8531 mydac(10);
void setup()
{
  Serial.begin(115200);
  mydac.selectVSPI();
  mydac.begin();
}
void loop()
{    
mydac.setValue(150);
}`

**Comment by RobTillaart** [comment]
![image](https://user-images.githubusercontent.com/462844/235226481-55b548d7-da8b-401f-bc93-7393fa4b5ea8.png)

So ccording to the datasheet the DAC8551 and DAC8531 should be compatible

**Comment by RobTillaart** [comment]
@guaizai2023 
Some posts suddenly disappeared  ?

**Comment by guaizai2023** [comment]
I found why my dac8531 module can not control,the ESP32 hardware VSPI did not turn on(I use the logic analyzer,The start signal of SPI no found ),I use software spi setGPIOPin() use my module successfully.And to DAC8531 module, if someone want to try it rail to rail function ,should use OPA703 but not LM358.`#include "DAC8551.h"
#include "Wire.h"
DAC8531 mydac(1);
void setup()
{
  Serial.begin(115200);
  mydac.selectVSPI();
  mydac.begin();
  mydac.setGPIOpins(18,2,23,5);
}
void loop()
{
    mydac.setValue(10000);
}`

**Comment by RobTillaart** [comment]
Sounds you got it working now, 
If so please close the issue/
